# site title
title: 纸笔人

# user name or organization name
user: WingLim

# issue repository
repository: Write

# multi-author
authors: WingLim

# token
# token should be separated by '#'
# example: 5#c31bffc137f44faf7efc4a84da827g7ca2cfeaa
token: 3#e77b6769f6e8379b32ddeae5f3cf4d80279b26a

# posts per page
perpage: 7


# advance config

# organization repository (?)
organization: false

# post order
# order by create time" or "update time"
# 'UPDATED_AT' or 'CREATED_AT'
order: 'CREATED_AT'
